### ISSUE TITLE
iOS compatibility

### ISSUE THREAD

**Issue by erich1510** [RohitBagda/SaveEggsGame#61]
Game doesn't accommodate wacky iPhone X notch screen size

iOS icons oddly rounded - the icon shows as the rounded icon plus white spaces on the edges

**Comment by RolandMunsil** [comment]
Do you have a screenshot of what it looks like on iPhone X?

**Comment by RolandMunsil** [comment]
bump @erich1510

**Comment by RohitBagda** [comment]
Resolved in latest test flight release
